### ISSUE TITLE
Update sample travis.yml

### ISSUE THREAD

**Issue by jayvdb** [coala/documentation#581]
The example travis.yml should be updated to be

```yaml
sudo: false
dist: xenial
language: generic
services: docker
script: docker run -v=$(pwd):/app --workdir=/app coala/base
```
